### ISSUE TITLE
I fixed the issue of newer version of ulauncher

### ISSUE THREAD

**Issue by Hedronmx** [PlugaruT/ulauncher-exit-elementary#4]
I dont know how to fork or pull request so I made my own repo

https://github.com/Hedronmx/ElementaryOSActions

Not sure how can I merge it to this?

**Comment by PlugaruT** [comment]
You should Fork this repo, the button is in the right top corner. Do the changes to your fork and then open a pull request to this repo. I will review and then merge if everything it's ok.

**Comment by Hedronmx** [comment]
Done
